### ISSUE TITLE
template_directory declaring after the XTECBlocs.js

### ISSUE THREAD

**Issue by armannadim** [projectestac/xtecblocs#2]
I'm installing this application in my local machine as a support of other application. Col·lex uses the ws of xtecblocs thats why I had to install it in local.
I found the following things irrelevant. I'm not sure if this theme is currently in use or not. But i guess Line 11 should be before Line 10. Because the variable template_directory is being used by the java script file XTECBlocs.js. It shows me referenceError if call "Template_directory" after calling the script XTECBlocs.js.

header.php
Line 9: <script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/prototype.js"></script>
Line 10: <script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/XTECBlocs.js"></script>
Line: 11: <script>var template_directory = <?php echo bloginfo('template_directory');?></script>

js/XTECBlocs.js
Line 1: var images=new Array(new Array(template_directory+'/css/img/cursos-i-proves.png','http://hipolit2.xtec.cat/blocs'), new Array(template_directory+'/css/img/help.png','index.php?a=help'))

Thank you :)

**Comment by toniginard** [comment]
The javascript error was caused by a feature that wasn't working and we are not going to use at the moment. We have commented all the code involved in this feature in order to remove all the errors while we decide if we keep this feature or not.

This is the commit to fix it: https://github.com/projectestac/xtecblocs/commit/7fcda2920e8053dac1a37b8ff6217852214edc51

Thanks for your contribution, Nadim!
